import { Track } from '../types';

export const DEFAULT_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Neon Horizon',
    artist: 'Cyber Pulse',
    bpm: 126,
    originalBpm: 126,
    key: 'F min',
    duration: 64,
    color: '#06b6d4', // Cyan
    sourceType: 'demo',
    intelligence: {
      energy: 72,
      danceability: 82,
      groove: 'rolling',
      intensity: 68,
      vocalDensity: 'medium',
      rhythmicDensity: 74,
      harmonicTension: 45,
      emotionalTone: 'euphoric',
      atmosphere: 'Late Night Festival Stage',
      genre: 'Melodic Techno',
      camelotKey: '4A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.4, y: 0.45 },
      tags: ['synth lead', 'vocal hook', 'punchy kick', 'melodic drop'],
    },
  },
  {
    id: 'track-2',
    title: 'Solar Eclipse',
    artist: 'Midnight Velocity',
    bpm: 128,
    originalBpm: 128,
    key: 'C min',
    duration: 64,
    color: '#ec4899', // Pink
    sourceType: 'demo',
    intelligence: {
      energy: 86,
      danceability: 91,
      groove: 'driving',
      intensity: 84,
      vocalDensity: 'high',
      rhythmicDensity: 88,
      harmonicTension: 62,
      emotionalTone: 'uplifting',
      atmosphere: 'Peak Hour Main Floor',
      genre: 'Tech House',
      camelotKey: '5A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.75, y: 0.82 },
      tags: ['peak tech', 'female vocal chop', 'rolling bassline', 'high energy'],
    },
  },
  {
    id: 'track-3',
    title: 'Bassline Pressure',
    artist: 'Underground Unit',
    bpm: 130,
    originalBpm: 130,
    key: 'G min',
    duration: 64,
    color: '#eab308', // Amber
    sourceType: 'demo',
    intelligence: {
      energy: 94,
      danceability: 95,
      groove: 'driving',
      intensity: 92,
      vocalDensity: 'low',
      rhythmicDensity: 94,
      harmonicTension: 75,
      emotionalTone: 'raw',
      atmosphere: 'Warehouse Rave',
      genre: 'Hardgroove & Peak Bass',
      camelotKey: '6A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.88, y: 0.94 },
      tags: ['heavy sub bass', 'driving ride cymbal', 'tribal claps', 'banger'],
    },
  },
  {
    id: 'track-4',
    title: 'Hyperdrive',
    artist: 'Future Rush',
    bpm: 174,
    originalBpm: 174,
    key: 'D min',
    duration: 64,
    color: '#a855f7', // Purple
    sourceType: 'demo',
    intelligence: {
      energy: 98,
      danceability: 89,
      groove: 'syncopated',
      intensity: 96,
      vocalDensity: 'low',
      rhythmicDensity: 98,
      harmonicTension: 80,
      emotionalTone: 'euphoric',
      atmosphere: 'Fast Pace High-Octane Arena',
      genre: 'Drum & Bass',
      camelotKey: '7A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.92, y: 0.96 },
      tags: ['breakbeat', 'amen chop', 'sub drop', 'reese bass'],
    },
  },
  {
    id: 'track-5',
    title: 'Sunset Groove',
    artist: 'Aura Sound',
    bpm: 122,
    originalBpm: 122,
    key: 'A min',
    duration: 64,
    color: '#10b981', // Emerald
    sourceType: 'demo',
    intelligence: {
      energy: 52,
      danceability: 76,
      groove: 'bouncy',
      intensity: 48,
      vocalDensity: 'medium',
      rhythmicDensity: 60,
      harmonicTension: 30,
      emotionalTone: 'warm',
      atmosphere: 'Sunset Beach Club Warmup',
      genre: 'Deep Organic House',
      camelotKey: '8A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.35, y: -0.2 },
      tags: ['warm chords', 'congas', 'melodic flute', 'chill vibe'],
    },
  },
  {
    id: 'track-6',
    title: 'Dark Matter Acid',
    artist: 'Berlin 303',
    bpm: 132,
    originalBpm: 132,
    key: 'E min',
    duration: 64,
    color: '#f97316', // Orange
    sourceType: 'demo',
    intelligence: {
      energy: 88,
      danceability: 86,
      groove: 'hypnotic',
      intensity: 90,
      vocalDensity: 'none',
      rhythmicDensity: 84,
      harmonicTension: 85,
      emotionalTone: 'dark',
      atmosphere: 'Industrial Basement Club',
      genre: 'Acid Techno',
      camelotKey: '9A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: -0.65, y: 0.78 },
      tags: ['tb-303 squelch', 'relentless kick', 'dark atmosphere', 'hypnotic'],
    },
  },
  {
    id: 'track-7',
    title: 'Celestial Dream',
    artist: 'Ethereal Voyage',
    bpm: 124,
    originalBpm: 124,
    key: 'C min',
    duration: 64,
    color: '#38bdf8', // Light blue
    sourceType: 'demo',
    intelligence: {
      energy: 58,
      danceability: 68,
      groove: 'atmospheric',
      intensity: 55,
      vocalDensity: 'acapella_drops',
      rhythmicDensity: 58,
      harmonicTension: 40,
      emotionalTone: 'melancholic',
      atmosphere: 'Open Air Sunrise Transition',
      genre: 'Progressive House',
      camelotKey: '5A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: -0.45, y: -0.15 },
      tags: ['dreamy pads', 'arpeggio', 'emotional breakdown', 'sunrise'],
    },
  },
  {
    id: 'track-8',
    title: 'Funk Matrix',
    artist: 'Groove Cartel',
    bpm: 125,
    originalBpm: 125,
    key: 'F min',
    duration: 64,
    color: '#e11d48', // Crimson Rose
    sourceType: 'demo',
    intelligence: {
      energy: 78,
      danceability: 96,
      groove: 'bouncy',
      intensity: 72,
      vocalDensity: 'high',
      rhythmicDensity: 82,
      harmonicTension: 35,
      emotionalTone: 'euphoric',
      atmosphere: 'Disco Glitz Party',
      genre: 'Nu-Disco / Jackin',
      camelotKey: '4A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.85, y: 0.35 },
      tags: ['slap bass', 'disco strings', 'vocal anthem', 'infectious groove'],
    },
  },
  {
    id: 'track-9',
    title: 'Abyssal Void',
    artist: 'Echoes of Sub',
    bpm: 120,
    originalBpm: 120,
    key: 'D min',
    duration: 64,
    color: '#6366f1', // Indigo
    sourceType: 'demo',
    intelligence: {
      energy: 44,
      danceability: 62,
      groove: 'hypnotic',
      intensity: 45,
      vocalDensity: 'none',
      rhythmicDensity: 50,
      harmonicTension: 70,
      emotionalTone: 'dark',
      atmosphere: 'Deep Minimal Chillout Room',
      genre: 'Dub Techno',
      camelotKey: '7A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: -0.75, y: -0.65 },
      tags: ['tape delay', 'sub rumble', 'chord stabs', 'deep space'],
    },
  },
  {
    id: 'track-10',
    title: 'Supernova Strike',
    artist: 'Valkyrie Sound',
    bpm: 134,
    originalBpm: 134,
    key: 'A min',
    duration: 64,
    color: '#14b8a6', // Teal
    sourceType: 'demo',
    intelligence: {
      energy: 92,
      danceability: 90,
      groove: 'rolling',
      intensity: 95,
      vocalDensity: 'medium',
      rhythmicDensity: 92,
      harmonicTension: 65,
      emotionalTone: 'uplifting',
      atmosphere: 'Stadium Festival Climax',
      genre: 'Peak Time Trance / Techno',
      camelotKey: '8A',
      structure: {
        intro: [0, 16],
        build: [16, 32],
        drop: [32, 48],
        breakdown: [48, 56],
        climax: [56, 64],
        outro: [60, 64],
        transitionPoints: [16, 32, 48, 56],
      },
      spaceCoords: { x: 0.6, y: 0.9 },
      tags: ['supersaw chords', 'laser sweeps', 'massive drop', 'hands in the air'],
    },
  },
];

